<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ResetMe.Platform</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResetMe.Core\ResetMe.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ResetMe.Core.Tests" />
  </ItemGroup>

</Project>
